"""Import loss functions to trigger their registration."""
from mist.loss_functions.losses.dice import DiceLoss  # noqa: F401
from mist.loss_functions.losses.dice_cross_entropy import DiceCELoss  # noqa: F401
from mist.loss_functions.losses.cl_dice import CLDice  # noqa: F401
from mist.loss_functions.losses.generalized_surface import GenSurfLoss  # noqa: F401
from mist.loss_functions.losses.boundary import BoundaryLoss  # noqa: F401
from mist.loss_functions.losses.hausdorff_one_sided import HDOneSidedLoss  # noqa: F401
from mist.loss_functions.losses.surface_dice_dilation import VolumetricSDDL  # noqa: F401
from mist.loss_functions.losses.surface_dice_dilation import VesselSDDL  # noqa: F401
